// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diveWebMVC.Models;

public partial class TCcourse
{
    public int CourseId { get; set; }

    public int? CourseCategoryId { get; set; }

    public int? LevelId { get; set; }

    public int? CoachId { get; set; }

    public decimal? CoursePrice { get; set; }

    public byte[] Photo { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual TMcoach Coach { get; set; }

    public virtual TCcourseCategory CourseCategory { get; set; }

    public virtual TCcourseLevel Level { get; set; }

    public virtual ICollection<TCorderDetail> TCorderDetails { get; set; } = new List<TCorderDetail>();
}