// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diveWebMVC.Models;

public partial class TCcourseLevel
{
    public int LevelId { get; set; }

    public string LevelName { get; set; }

    public virtual ICollection<TCcourse> TCcourses { get; set; } = new List<TCcourse>();
}