// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diveWebMVC.Models;

public partial class TCorderDetail
{
    public int OrderDetailId { get; set; }

    public int? OrderId { get; set; }

    public int? CourseId { get; set; }

    public decimal? CoursePrice { get; set; }

    public int? Quantity { get; set; }

    public virtual TCcourse Course { get; set; }

    public virtual TCorder Order { get; set; }
}