// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diveWebMVC.Models;

public partial class TCorder
{
    public int OrderId { get; set; }

    public int? MemberId { get; set; }

    public DateTime? OrderDate { get; set; }

    public virtual TMmemberList Member { get; set; }

    public virtual ICollection<TCorderDetail> TCorderDetails { get; set; } = new List<TCorderDetail>();
}