// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diveWebMVC.Models;

public partial class TMdivingLevel
{
    public int LevelId { get; set; }

    public string LevelType { get; set; }

    public int? LevelNameId { get; set; }

    public virtual TMdivingLevelName LevelName { get; set; }

    public virtual ICollection<TMcoachDivingLevel> TMcoachDivingLevels { get; set; } = new List<TMcoachDivingLevel>();

    public virtual ICollection<TMmemberDivingLevel> TMmemberDivingLevels { get; set; } = new List<TMmemberDivingLevel>();
}