// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diveWebMVC.Models;

public partial class TMdivingStyle
{
    public int DivingStyleId { get; set; }

    public string DivingStyle { get; set; }

    public virtual ICollection<TMcoachDiving> TMcoachDivings { get; set; } = new List<TMcoachDiving>();
}