// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diveWebMVC.Models;

public partial class TMfavoriteList
{
    public int FavoriteId { get; set; }

    public int? MemberId { get; set; }

    public int? FavoriteItem { get; set; }

    public DateOnly? CreateDate { get; set; }

    public virtual TMmemberList Member { get; set; }
}