// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diveWebMVC.Models;

public partial class TMmemberDivingLevel
{
    public int DivingLevelId { get; set; }

    public int? LevelId { get; set; }

    public int? MemberId { get; set; }

    public virtual TMdivingLevel Level { get; set; }

    public virtual TMmemberList Member { get; set; }
}