// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diveWebMVC.Models;

public partial class TNorder
{
    public int OrderId { get; set; }

    public int? MemberId { get; set; }

    public DateTime? OrderDate { get; set; }

    public string Address { get; set; }

    public string OrderStatus { get; set; }

    public string PaymentStatus { get; set; }

    public decimal? TotalAmount { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual TMmemberList Member { get; set; }

    public virtual ICollection<TNorderDetail> TNorderDetails { get; set; } = new List<TNorderDetail>();
}