// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diveWebMVC.Models;

public partial class TNorderDetail
{
    public int OrderDetailsId { get; set; }

    public int? OrderId { get; set; }

    public int? ProductvariantsId { get; set; }

    public int? Quantity { get; set; }

    public decimal? UnitPrIce { get; set; }

    public decimal? TotalPrice { get; set; }

    public virtual TNorder Order { get; set; }

    public virtual TNproductvariant Productvariants { get; set; }
}