// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diveWebMVC.Models;

public partial class TNpicture
{
    public int PictureId { get; set; }

    public int? ProductId { get; set; }

    public byte[] Image { get; set; }

    public virtual TNproduct Product { get; set; }
}