// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diveWebMVC.Models;

public partial class TSsiteDetail
{
    public int SiteId { get; set; }

    public string VenueName { get; set; }

    public int? NumberOfPeople { get; set; }

    public string VenueAddress { get; set; }

    public string Detail { get; set; }

    public string State { get; set; }

    public virtual ICollection<TSorder> TSorders { get; set; } = new List<TSorder>();

    public virtual ICollection<TSphoto> TSphotos { get; set; } = new List<TSphoto>();
}