// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diveWebMVC.Models;

public partial class TUorderStatusId
{
    public int OrderStatusId { get; set; }

    public string PaymentStatus { get; set; }

    public virtual ICollection<TUorderLog> TUorderLogs { get; set; } = new List<TUorderLog>();
}