// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diveWebMVC.Models;

public partial class TUproductCondition
{
    public int ProductConditionId { get; set; }

    public string Condition { get; set; }

    public virtual ICollection<TUproduct> TUproducts { get; set; } = new List<TUproduct>();
}